# Generated by Django 2.1.7 on 2019-02-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户扩展信息', 'verbose_name_plural': '用户扩展信息'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机'),
        ),
    ]
